# Format: https://dart.dev/tools/pub/pubspec.

name: scrap
verison: 0.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  jsonut: ^0.3.0
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  jsonut:
    path:
      ../../../jsonut
