# Format: https://dart.dev/tools/pub/pubspec.

name: jawa
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.2
  crypto: ^3.0.3
  http: ^1.2.1
  intl: ^0.19.0
  jsonut: ^0.4.0
  meta: ^1.12.0
  path: ^1.9.0
  scrap:
    path: ../scrap
  stack_trace: ^1.11.1

dev_dependencies:
  lints: ^3.0.0
