name: app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  collection: ^1.18.0
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_file_saver: ^0.6.2
  flutter_svg: ^2.0.10+1
  foil: ^0.9.0+1
  jsonut: ^0.4.0
  meta: ^1.11.0
  unlimited:
    path: ../unlimited

dev_dependencies:
  args: ^2.4.2
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/empire.svg
    - assets/rebels.svg
