# Format: https://dart.dev/tools/pub/pubspec.

name: unlimited
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.12.0

dev_dependencies:
  checks: ^0.3.0
  jsonut: ^0.4.0
  lints: ^3.0.0
  path: ^1.9.0
  scrap:
    path: ../scrap
  test: ^1.25.2
