# Format: https://dart.dev/tools/pub/pubspec.

name: superlaser
version: 0.0.0
description: >
  A runtime library and command-line interface for Star Wars: Unlimited

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
