# See https://docs.github.com/en/actions.

name: flutter CI
run-name: Validating and deploying builds on GitHub Actions

# When a commit is merged into the main branch (i.e. post-submit).
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./packages/superlaser_app
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build PWA
        run: flutter build web --release

      - name: Build docs for "package:unlimited"
        # If I point to ../unlimited with "dart doc", src libraries are included in the docs.
        # TODO: Re-add "--validate-links".
        run: cd ../unlimited && dart doc --output "./build/web/docs"
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/superlaser_app/build/web
          publish_branch: latest
